SKU=$1
ADIE=$2
RT28xx_BIN_DIR=$3
echo $SKU
echo $ADIE
echo $RT28xx_BIN_DIR
RT28xx_DIR=$RT28xx_BIN_DIR/mt_wifi
CHIPSET=mt7986
RT28xx_MODE=AP
HAS_WOW_SUPPORT=n
HAS_FPGA_MODE=n
HAS_RX_CUT_THROUGH=n
export RT28xx_DIR CHIPSET RT28xx_MODE HAS_WOW_SUPPORT HAS_FPGA_MODE HAS_RX_CUT_THROUGH RT28xx_BIN_DIR SKU ADIE
$RT28xx_BIN_DIR/mt_wifi/embedded/tools/bin2h
